name = "Terrassa"
license = "MIT"
licenselink = "https://github.com/danielkvist/hugo-terrassa-theme/blob/master/LICENSE"
description = "A simple, fast and responsive theme for Hugo with a strong focus on accessibility."
homepage = "http://github.com/danielkvist/hugo-terrassa-theme"
tags = ["gimt", "coding_club", "portfolio", "web_dev", "5th_Sem_3rd Sem", "opensource", "git", "github"]
features = [
  "responsive design",
  "accessibility",
  "social icons",
  "contact form",
  "blog",
]
min_version = "0.41"

[author]
  name = "Danielkvist (Daniel Zaragoza)"
  homepage = "https://dkvist.com"
